version: "3.8"

services:
  postgres:
    image: postgres:16-alpine
    container_name: invt_mgmt_db
    restart: unless-stopped
    ports:
      - "5444:5432"
    environment:
      POSTGRES_DB: invt_mgmt_db
      POSTGRES_USER: invtMgmtUser
      POSTGRES_PASSWORD: invtMgmtUser@2k26
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
